# .github/workflows/standard-ci.yml

name: Workflow Reutilizable
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: '20'

jobs:
  job-principal:
    runs-on: ubuntu-latest
    steps:
      - name: Llamada a mi bloque compuesto
        uses: valentechy/github-actions-gobernanza/actions/setup-node-security@main
        with:
          node-version: ${{ inputs.version }}
      - name: Build
        run: npm run build
